#!/bin/sh

set -eo pipefail

action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME
param=${CNAB_P_HELLO}

az login --service-principal -u $APP_ID -p ${PASSWORD} --tenant ${TENANT_DNS} 
echo "====================== logged into Azure ============================"
echo 

case $action in
    install)
    echo "====================== Installation ============================"

    az iot edge deployment create --deployment-id "$DEPLOYMENT_ID" --hub-name "$HUB_NAME" --content /cnab/app/deploy/sql-deployment.json --target-condition "tags.name = '$CONDITION'"
    ;;
    com.azure.iot.undeploy)
    echo "====================== Uninstallation ============================"


    az iot edge deployment create --deployment-id no-"$DEPLOYMENT_ID" --hub-name "$HUB_NAME" --content /cnab/app/deploy/undeployment.json --target-condition "tags.name = '$CONDITION'"
    ;;
    upgrade)
    echo "====================== Uninstallation ============================"

    az iot edge deployment update --deployment-id "$DEPLOYMENT_ID" --hub-name "$HUB_NAME" --content /cnab/app/deploy/undeployment.json --target-condition "tags.name = '$CONDITION'"
    ;;
    downgrade)
    echo "Downgrade action"
    ;;
    status)
    echo "====================== Deployment Status ============================"
    az iot edge deployment list -g "$AZURE_RESOURCE_GROUP" -n "$HUB_NAME" --query '[].{ID:id,Applied:systemMetrics.results.appliedCount,Targeted:systemMetrics.results.targetedCount,Failed:systemMetrics.results.reportedFailedCount,Succeeded:systemMetrics.results.reportedSuccessfulCount,Target:targetCondition,Created:createdTimeUtc,Updated:lastUpdatedTimeUtc}' -o table

    ;;
    uninstall)
    echo "The uninstall command has no effect in Azure IoT scenarios. Consider one of the other commands."
    ;;
    com.azure.iot.deploy-purge)
    echo "====================== Purging deployments for target: tags.name == '$CONDITION' ========================="
    az iot edge deployment list -g "$AZURE_RESOURCE_GROUP" -n "$HUB_NAME" --query '[].id' -o tsv | xargs -I {} az iot edge deployment delete -g "$AZURE_RESOURCE_GROUP" -d {} -n "$HUB_NAME"
    ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"